english = {
    #WeaponDB stats:
    "rateoffire": "Rate Of Fire",
    "projectilebreakingangle": "Projectile Breaking Angle",
    "zero": "Zero",
    "range": "Range",
    "damage": "Damage",
    "penetration1": "Penetration",
    "penetration2": "Penetration Ratio",
    "velocity1": "Muzzle Velocity",
    "velocity2": "Muzzle Velocity",
    "recoilpivot": "Recoil Pivot",
    "ui_accuracy": "Accuracy",
    "ui_control": "Control",
    "ui_range": "Range",
    "ui_rateoffire": "Rate Of Fire",
    "ui_unknown1": "Unknown UI Float",
    "ui_unknown2": "Unknown UI Float",
    "ui_mobility": "Mobility",
    "ui_recoil": "Recoil",
    "timetoaim": "Time To Aim",
    "burdenfactor": "Burden Factor",
    "sway": '"Sway"',
    "modulatedspreadmax": "Modulated Spread Max",
    "modulatedspreadmin": "Modulated Spread Min",
    "modulatedspreadironsights": "Modulated Spread Ironsights",
    "ironsightspreadmultiplier": "Ironsight Spread Multiplier",
    "otsspreadmultiplier": "OTS Spread Multiplier",
    "spreadradiusmin": "Spread Radius Min",
    "spreadradiusmax": "Spread Radius Max",
    "spreadtimetomin": "Spread Time to Min",
    "spreadtimetomax": "Spread Time to Max",
    "gaussironsight": "Gauss Ironsight",
    "gaussinstinct": "Gauss Instinct",
    "gaussots": "Gauss OTS",
    "recoilpattern": "Recoil Pattern",
    "soundfile": "Sound File",
    "tacticalreloadthreshold": "Tactical Reload Threshold",
    "walkspeedmultiplier": "Walk Speed Multiplier",
    "mobility": "Mobility",
    "adssensitivity": "ADS Sensitivity Multiplier",
    "soundrange": "Sound Range",
    "bulletdb": "Bullet DB",
    "reloadtime": "Reload Time",
    "ammotype": "Ammo Type",
    "spreadpattern": "Spread Pattern",
    #Buttons:
    "copyu64": "Copy file's u64 value to clipboard",
    "ignore": "Ignore",
    "apply": "Apply",
    "calculate": "Calculate",
    "revertoriginal": "Revert to\noriginal",
    #Text:
    0: 'Close', # for closing the program or window
    1: 'ERROR: Could not read settings',
    2: 'Could not read or create settings.json. Try deleting it from the folder the .exe is in, if it already exists.',
    3: "\n\nThe report button copies the log to the clipboard and opens the bugpage on nexusmods in your browser. Simply paste it into a report and tell me what you were doing.",
    4: 'Report bug',
    5: "Open", # A file
    6: "Revert",
    7: 'Unknown File',  
    8: 'The file you have selected, is unknown. The file format is known, so you can try to use the current searchpattern, but results might not be correct and changes might corrupt the file.\n\n Continue?',
    9: 'Yes',
    10: 'No',
    11: "Unsupported File",
    12: "GRB Editor v0.1", # Window title
    13: "Please open a file",
    14: "The selected file did not get recognized as a supported fileformat by the program.",
    15: 'OK',
    16: 'Print File',
    19: ["Warning", "Any changes to the current file that has not been written, will be lost."],
}